// Data for each hero category
export const heroData = {
  "weight-loss": {
    categoryName: "Weight Loss",
    solutionsText: "you lose weight effectively and safely",
    goalsText: "weight loss",
    mainColor: "#D6FEA1",
    backgroundColor: "#547553",
    buttonIcon: "https://www.vitabella.com/wp-content/uploads/2025/02/icon-1.svg",
    backgroundImage: "https://www.vitabella.com/wp-content/uploads/2025/03/bg-container_result.webp",
    mobileImage: "https://www.vitabella.com/wp-content/uploads/2025/04/WeightLossMobile3.webp",
    mainImage: "https://www.vitabella.com/wp-content/uploads/2025/04/WeightLossDesktop2.webp",
  },
  "hormone-therapy": {
    categoryName: "Hormone Therapy",
    solutionsText: "optimize hormones and fertility",
    goalsText: "hormone therapy",
    mainColor: "#CEE9FF",
    backgroundColor: "#4263AE",
    buttonIcon: "https://www.vitabella.com/wp-content/uploads/2025/03/blue-arrow-1.svg",
    backgroundImage: "https://www.vitabella.com/wp-content/uploads/2025/04/slider4.webp",
    mobileImage: "https://www.vitabella.com/wp-content/uploads/2025/04/HormoneTherapyMobile.webp",
    mainImage: "https://www.vitabella.com/wp-content/uploads/2025/04/HormoneDesktop.webp",
  },
  "anti-aging": {
    categoryName: "Anti-Aging",
    solutionsText: "you improve healthspan and lifespan",
    goalsText: "longevity",
    mainColor: "#FAEDCD",
    backgroundColor: "#B16F38",
    buttonIcon: "https://www.vitabella.com/wp-content/uploads/2025/03/grey-arrow.svg",
    backgroundImage: "https://www.vitabella.com/wp-content/uploads/2025/04/ANTI-AGING.webp",
    mobileImage: "https://www.vitabella.com/wp-content/uploads/2025/04/AntiAgingMobile.webp",
    mainImage: "https://www.vitabella.com/wp-content/uploads/2025/04/AntiAgingDesktop.webp",
  },
  "sexual-wellness": {
    categoryName: "Sexual Wellness",
    solutionsText: "improve sexual function and intimacy",
    goalsText: "sexual wellness",
    mainColor: "#FFBBB7",
    backgroundColor: "#831435",
    buttonIcon: "https://www.vitabella.com/wp-content/uploads/2025/03/dark-pink-arrow.svg",
    backgroundImage: "https://www.vitabella.com/wp-content/uploads/2025/04/bg-container-1.webp",
    mobileImage: "https://www.vitabella.com/wp-content/uploads/2025/04/SexualWellnessMobile3.webp",
    mainImage: "https://www.vitabella.com/wp-content/uploads/2025/04/SexualWellnessDesktop-1.webp",
  },
  "cognitive-health": {
    categoryName: "Cognitive Health",
    solutionsText: "improve brain function and cognition",
    goalsText: "cognitive health",
    mainColor: "#CEE9FF",
    backgroundColor: "#40699E",
    buttonIcon: "https://www.vitabella.com/wp-content/uploads/2025/03/blue-arrow-1.svg",
    backgroundImage: "https://www.vitabella.com/wp-content/uploads/2025/04/blue-color.webp",
    mobileImage: "https://www.vitabella.com/wp-content/uploads/2025/04/CognitiveHealthMobile.webp",
    mainImage: "https://www.vitabella.com/wp-content/uploads/2025/04/CognitiveHealthDesktop2.webp",
  },
  "hair-loss": {
    categoryName: "Hair Loss",
    solutionsText: "sustain and improve hair growth",
    goalsText: "hair growth",
    mainColor: "#FFD19F",
    backgroundColor: "#98312B",
    buttonIcon: "https://www.vitabella.com/wp-content/uploads/2025/03/maroon-arrow.svg",
    backgroundImage: "https://www.vitabella.com/wp-content/uploads/2025/04/meroon.webp",
    mobileImage: "https://www.vitabella.com/wp-content/uploads/2025/04/HairLossMobile3.webp",
    mainImage: "https://www.vitabella.com/wp-content/uploads/2025/04/HairLossDesktop.webp",
  },
  "injury-recovery": {
    categoryName: "Injury & Recovery",
    solutionsText: "turn your injury setback into a comeback",
    goalsText: "recovery",
    mainColor: "#DBFFEE",
    backgroundColor: "#76AC94",
    buttonIcon: "https://www.vitabella.com/wp-content/uploads/2025/03/dark-green-arrow.svg",
    backgroundImage: "https://www.vitabella.com/wp-content/uploads/2025/04/lightgreen-color.webp",
    mobileImage: "https://www.vitabella.com/wp-content/uploads/2025/04/InjuryMobile.webp",
    mainImage: "https://www.vitabella.com/wp-content/uploads/2025/04/InjuryDesktop.webp",
  },
  "skin-care": {
    categoryName: "Skin Care",
    solutionsText: "boost confidence with healthy, glowing skin",
    goalsText: "skin care",
    mainColor: "#FAEDCD",
    backgroundColor: "#CF8F59",
    buttonIcon: "https://www.vitabella.com/wp-content/uploads/2025/03/skin-care-arrow.svg",
    backgroundImage: "https://www.vitabella.com/wp-content/uploads/2025/03/bg-container-1_result.webp",
    mobileImage: "https://www.vitabella.com/wp-content/uploads/2025/04/SkinCareMobile.webp",
    mainImage: "https://www.vitabella.com/wp-content/uploads/2025/04/SkinCareDesktop.webp",
  },
};
