// Data for each hero category
export const heroData = {
  "weight-loss": {
    categoryName: "Weight Loss",
    slug: "weight-loss",
    solutionsText: "you lose weight effectively and safely",
    goalsText: "weight loss",
    mainColor: "#D6FEA1",
    backgroundColor: "#547553",
    buttonIcon: "/modules/hero/weightlossarrow.svg",
    backgroundImage: "/modules/hero/weightlossbg.webp",
    mobileImage: "/modules/hero/weightlossmobile.webp",
    mainImage: "/modules/hero/weightloss.webp",
    pointOne: "Look and feel better than ever before with renewed confidence",
    pointTwo: "Licensed providers offering personalized and individualized care for your weight loss needs",
    pointThree: "Top-quality medication shipped discreetly to your door from U.S. pharmacies"
  },
  "hormone-therapy": {
    categoryName: "Hormone Therapy",
    slug: "hormone-therapy",
    solutionsText: "optimize hormones and fertility",
    goalsText: "hormone therapy",
    mainColor: "#CEE9FF",
    backgroundColor: "#4263AE",
    buttonIcon: "/modules/hero/hormonetherapyarrow.svg",
    backgroundImage: "/modules/hero/hormonetherapybg.webp",
    mobileImage: "/modules/hero/hormonetherapymobile.webp",
    mainImage: "/modules/hero/hormonetherapy.webp",
    pointOne: "Optimize your hormones and energy levels, improve lean muscle mass and support bone density.",
    pointTwo: "Licensed providers offering personalized and individualized care for your hormone therapy needs",
    pointThree: "Top-quality medication shipped discreetly to your door from U.S. pharmacies"
  },
  "anti-aging": {
    categoryName: "Anti-Aging",
    slug: "anti-aging",
    solutionsText: "you improve healthspan and lifespan",
    goalsText: "longevity",
    mainColor: "#FAEDCD",
    backgroundColor: "#B16F38",
    buttonIcon: "/modules/hero/antiagingarrow.svg",
    backgroundImage: "/modules/hero/antiagingbg.webp",
    mobileImage: "/modules/hero/antiagingmobile.webp",
    mainImage: "/modules/hero/antiaging.webp",
    pointOne: "Boost daily vitality and reduce fatigue while improving memory, focus, and mental clarity",
    pointTwo: "Licensed providers offering personalized and individualized care for your anti-aging needs",
    pointThree: "Top-quality medication shipped discreetly to your door from U.S. pharmacies"
  },
  "sexual-wellness": {
    categoryName: "Sexual Wellness",
    slug: "sexual-wellness",
    solutionsText: "improve sexual function and intimacy",
    goalsText: "sexual wellness",
    mainColor: "#FFBBB7",
    backgroundColor: "#831435",
    buttonIcon: "/modules/hero/sexualwellnessarrow.svg",
    backgroundImage: "/modules/hero/sexualwellnessbg.webp",
    mobileImage: "/modules/hero/sexualwellnessmobile.webp",
    mainImage: "/modules/hero/sexualwellness.webp",
    pointOne: "Solutions that offer long-lasting effects without prescription limitations",
    pointTwo: "Licensed providers offering personalized and individualized care for your sexual wellness needs",
    pointThree: "Top-quality medication shipped discreetly to your door from U.S. pharmacies"
  },
  "cognitive-health": {
    categoryName: "Cognitive Health",
    slug: "cognitive-health",
    solutionsText: "improve brain function and cognition",
    goalsText: "cognitive health",
    mainColor: "#CEE9FF",
    backgroundColor: "#40699E",
    buttonIcon: "/modules/hero/hormonetherapyarrow.svg",
    backgroundImage: "/modules/hero/cognitivehealthbg.webp",
    mobileImage: "/modules/hero/cognitivehealthmobile.webp",
    mainImage: "/modules/hero/cognitivehealth.webp",
    pointOne: "Boost memory recall and sharpen learning abilities while improving motor and emotional functions.",
    pointTwo: "Licensed providers offering personalized and individualized care for your cognitive health needs",
    pointThree: "Top-quality medication shipped discreetly to your door from U.S. pharmacies"
  },
  "hair-loss": {
    categoryName: "Hair Loss",
    slug: "hair-loss",
    solutionsText: "sustain and improve hair growth",
    goalsText: "hair growth",
    mainColor: "#FFD19F",
    backgroundColor: "#98312B",
    buttonIcon: "/modules/hero/hairlossarrow.svg",
    backgroundImage: "/modules/hero/hairlossbg.webp",
    mobileImage: "/modules/hero/hairlossmobile.webp",
    mainImage: "/modules/hero/hairloss.webp",
    pointOne: "Revitalize your hair growth and regain thicker, stronger hair while targeting root causes",
    pointTwo: "Licensed providers offering personalized and individualized care for your hair loss treatment needs",
    pointThree: "Top-quality medication shipped discreetly to your door from U.S. pharmacies"
  },
  "injury-recovery": {
    categoryName: "Injury & Recovery",
    slug: "injury-and-recovery",
    solutionsText: "turn your injury setback into a comeback",
    goalsText: "recovery",
    mainColor: "#DBFFEE",
    backgroundColor: "#76AC94",
    buttonIcon: "/modules/hero/injuryrecoveryarrow.svg",
    backgroundImage: "/modules/hero/injuryrecoverybg.webp",
    mobileImage: "/modules/hero/injuryrecoverymobile.webp",
    mainImage: "/modules/hero/injuryrecovery.webp",
    pointOne: "Help repair muscle, increase bone density, reduce fat distribution, and address your distinct needs",
    pointTwo: "Licensed providers offering personalized and individualized care for your hormone therapy needs",
    pointThree: "Top-quality medication shipped discreetly to your door from U.S. pharmacies"
  },
  "skin-care": {
    categoryName: "Skin Care",
    slug: "skin-care",
    solutionsText: "boost confidence with healthy, glowing skin",
    goalsText: "skin care",
    mainColor: "#FAEDCD",
    backgroundColor: "#CF8F59",
    buttonIcon: "/modules/hero/skincarearrow.svg",
    backgroundImage: "/modules/hero/skincarebg.webp",
    mobileImage: "/modules/hero/skincaremobile.webp",
    mainImage: "/modules/hero/skincare.webp",
    pointOne: "Reduce fine lines and wrinkles while retaining moisture to prevent skin dehydration and sagging.",
    pointTwo: "Licensed providers offering personalized and individualized care for your hormone therapy needs",
    pointThree: "Top-quality medication shipped discreetly to your door from U.S. pharmacies"
  },
};
