import React from 'react';
import { CONTACT_EMAIL } from '../../constants/contacts';

const TermsOfService: React.FC = () => {
    return (
        <div
            className="terms-of-service"
            style={{
            maxWidth: 1340 / 2,
            margin: 'var(--space-3x) auto',
            padding: 'var(--space-2x)',
            textAlign: 'justify',
            }}
        >
            <h1>Terms of Service</h1>
            <p><strong>V1.3 Updated 07.23.2024</strong></p>

            <p><strong>Important:</strong> This is a contract between you and Vita Bella Health, LLC (“Vita Bella” or “We” or “Us” or “Our”) for the provision of the Services as defined below (the “Agreement”).</p>

            <p>Please read the Agreement carefully before your first appointment with a Vita Bella provider. By accessing Services through Vita Bella, you acknowledge that:</p>
            <ul>
                <li>You are at least 18 years of age,</li>
                <li>You have read this agreement,</li>
                <li>You understand it,</li>
                <li>You accept and agree to be bound by its terms,</li>
                <li>Your provider may recommend a scheduled and/or unregulated drug or compound depending on your condition(s). You understand that such drug or compound may cause certain side effects which your healthcare provider will explain to you which may vary depending on other medications you take. Vita Bella will not dispense such drugs or compounds to you. If you purchase any recommended drugs or compounds from one of our online pharmacy partners, your purchase will be subject to that pharmacy’s terms and privacy practices, not ours.</li>
                <li>You represent and warrant that you will provide your provider with a complete and accurate list of your health conditions, medical history, and current medications. You agree to hold Vita Bella harmless from responsibility for any adverse effect you experience because of your failure to provide us with complete and accurate information. <strong>VITA BELLA IS NOT AND CANNOT BE HELD RESPONSIBLE FOR THE QUALITY OR EFFICACY OF ANY DRUGS OR COMPOUNDS DISPENSED TO YOU.</strong></li>
            </ul>

            <p>If you do not agree, do not understand, or do not accept this Agreement, please do not create an account and do not access any of the below Services. If you have questions or concerns, contact Vita Bella at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p>

            <h2>Our Practices</h2>
            <h3>Section 1</h3>
            <p>Vita Bella is a management organization that partners with medical practices (the “Practices”) to provide our clients with access to various healthcare services. The Practices offer telehealth-based health and wellness services, including weight loss, strength & conditioning, healthy aging, injury & recovery, cognitive health and sexual wellness. We also connect you with online pharmacies to fulfill the prescriptions you need (collectively with the telehealth-based health and wellness services, the “Services”).</p>
            <p>Vita Bella does <strong>NOT</strong> own the practices, nor does Vita Bella employ the clinicians that treat you. Vita Bella is <strong>NOT</strong> a healthcare provider.</p>

            <h2>Packages And Fees</h2>
            <h3>Section 2</h3>
            <p><strong>Membership Packages.</strong> Under the terms of this Agreement, Vita Bella will provide you with access to the Services based upon your selected membership tier (the “Membership Packages”). This Agreement incorporates the time-commitment, services, pricing, and termination language present in the Membership Packages.</p>
            <p><strong>Access to Pharmacy Care.</strong> While We are not a pharmacy, We coordinate with several pharmacies (“Preferred Pharmacy”) through which you can obtain any medications your provider prescribes for you. Through your account with Us, we will automatically transmit your prescriptions to the pharmacy and we will charge you for the cost of the medication. By agreeing to these Terms, you authorize Vita Bella to automatically charge the credit card on file for any medication ordered through Vita Bella. The pharmacy will then process your prescription and mail your medications to you. If you do not wish to fill your prescription through a Preferred Pharmacy, Vita Bella will transmit your prescription to the pharmacy of your choosing but will charge you a one hundred five dollar ($125.00) processing fee for such transfer. <strong>VITA BELLA IS NOT A PHARMACY. WE DO NOT COMPOUND OR DISTRIBUTE DRUGS. WE ARE NOT RESPONSIBLE FOR ANY LOST PACKAGES, ADDRESS ERRORS, QUALITY ERRORS, OR OTHER DEFICIENCIES OR ERRORS IN THE MEDICATIONS YOU RECEIVE. WE CANNOT GUARANTEE DELIVERY DATES AND CANNOT CONTROL EXTENUATING CIRCUMSTANCES THAT COULD DELAY YOUR PACKAGE SUCH AS INCLEMENT WEATHER. THERE ARE NO REFUNDS ON MEDICATIONS. IF YOU HAVE A QUESTION ABOUT YOUR MEDICATION SHIPMENT, CONTACT THE PHARMACY.</strong></p>
            <p><strong>Access to Laboratory Services.</strong> Vita Bella may provide you with a written order for laboratory services as needed depending upon your Membership Package and your clinical needs. Lab services may include without limitation orders for pathology labs, clinical labs, and any other laboratory services that are reasonably necessary for Vita Bella to provide you with the Services. Vita Bella will either i) provide you with an order for you to take to a laboratory of your choice or ii) transmit an order to one of our preferred laboratories for you.</p>
            <p><strong>Minimum Commitment.</strong> Your initial Membership Package requires a 6-month minimum commitment. Following your initial package, your membership will renew on a month-to-month basis until you terminate in accordance with these Terms.</p>
            <p><strong>Membership Tiers.</strong> Vita Bella offers different membership tiers based on the level of services you need and wish to receive. If you wish to change tiers before your current Membership Package expires, you may do so by managing your account in Stripe.</p>

            <h2>Monthly Fee and Payment</h2>
            <h3>Section 3</h3>
            <p><strong>Monthly Fee.</strong> You are responsible for all fees associated with your chosen Membership Package (the “Monthly Fees”). Vita Bella may update the Monthly Fee from time to time, but you will not be charged the updated fee until your account renews. We will always let you know ahead of time if our fees have changed since your last renewal, and you will have the option to cancel your account before we charge you the new fee.</p>
            <p><strong>Auto-renew.</strong> Your Membership Package will automatically renew on a monthly basis until you cancel in accordance with Section 4 below. You acknowledge that selecting a Membership Package requires a recurring payment and you accept responsibility for all recurring charges accrued prior to termination of your account. You must terminate your Membership before it renews in order to avoid being charged for the next billing cycle.</p>
            <p>Vita Bella accepts payment via credit or debit card and provides you with an option to enroll in autopay. By enrolling in autopay, you authorize Vita Bella to initiate recurring automated charges to your chosen payment method each month at the then-current Monthly Fee rate until you cancel or terminate your account in accordance with Section 4 below. By enrolling in autopay, you authorize Vita Bella to maintain your payment information that you submit to Us. You can update your payment method through Stripe.</p>
            <p><strong>No Refunds.</strong> Vita Bella has a strict no-refund policy, including in the event of termination of your membership by Vita Bella if you breach this agreement, the Terms of Use, or the Privacy Policy. By entering into this Agreement, you agree and understand that you are permanently waiving the right to seek or claim any refund of any fees paid to Vita Bella prior to termination.</p>
            <p><strong>No-Show Fees.</strong> Our providers time is valuable. If you cannot make an appointment, please notify us within 24 hours of the appointment time or a $50 non-refundable cancellation/no-show fee will be automatically charged to the card on file.</p>
            <p><strong>Switching to a Higher Membership Tier.</strong> If you choose to switch from a lower membership tier to a higher tier at any time, you will be required to commit to a 6-month membership at the higher tier. If you choose to switch prior to the expiration of your current membership, you will have immediate access to the higher tier and you will be charged a prorated fee for the remainder of the then-current month. For example, if your current plan is $99 per month and you choose to switch to a higher tier membership for $179 per month on the 16th day of a 30-day period, you will owe $50 for days 1-15 and $89 for days 16-30.</p>
            <p><strong>Switching to a Lower Membership Tier.</strong> If you choose to switch from a higher membership tier to a lower tier at any time, you will not be required to commit to a 6-month membership at the lower tier. You will be charged a prorated fee for the remainder of your existing membership and thereafter. For example, if your current plan is $179 per month and you choose to switch to a lower tier membership for $99 per month on the 16th day of the 5th month in your Initial 6-month period, you will owe $89 for days 1-15 and $50 for days 16-30 for a total of $139.</p>

            <h2>Account Term & Termination</h2>
            <h3>Section 4</h3>
            <p><strong>Account Term.</strong> Your account and this Agreement will be effective as soon as you create your account, accept the terms of this Agreement, and submit your first Monthly Fee payment. You will be charged each month unless and until you tell us you want to cancel. you may cancel at any time by contacting <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p>
            <p><strong>Terminating your Account.</strong> You may terminate your account at any time. If you terminate your account, your account will terminate at the end of the then-current membership term. For 6-month Packages, your account will terminate at the end of the sixth month. For month-to-month renewal periods, your account will terminate at the end of the month in which you terminate. You will have access to the Services and will remain responsible for all fees until termination is effective. Vita Bella may immediately terminate your account at any time in its discretion upon written notice to you, which may be sent via email, in accordance with applicable state law.</p>
            <p>Terminating treatment prior to the end of a recommended treatment plan may be harmful to you. If you decide to stop treatment before the end of your recommended treatment plan (typically 6 months). If you choose to stop accessing the Services prior to the end of your recommended treatment plan, you are responsible for any adverse health effects of doing so. <strong>VITA BELLA IS NOT AND CANNOT BE HELD RESPONSIBLE FOR ANY ADVERSE HEALTH OUTCOMES YOU EXPERIENCE AS A RESULT OF YOUR CHOICE TO STOP TREATMENT EARLY OR YOUR FAILURE TO COMPLETE YOUR RECOMMENDED TREATMENT PLAN.</strong></p>
            <p>The provisions of this Agreement concerning indemnification, non-disclosure, Confidential Information, Intellectual Property, disclaimer of warranties, and limitation of liability shall survive the termination of this Agreement. Upon expiration or termination of this Agreement for any reason, (a) your access to the Services and all Vita Bella materials and information will cease; and (b) Vita Bella’s obligations under this Agreement will also cease.</p>
            <p><strong>Promotional Material.</strong> Vita Bella or the Practices may, from time to time, ask you to provide a testimonial about your experience with Vita Bella and/or a Practice (each, a “Testimonial”) and Vita Bella or a Practice may share your Testimonial for marketing or other purposes. Before sharing, we will anonymize your Testimonial by using your initials or first name only unless you give us permission to share your identity. you represent and warrant that any Testimonials that you make will be correct, accurate, and truthful. Further, by providing a Testimonial you license to Vita Bella or the Practices the right to use the Testimonials and your first name and initials to use, broadcast, distribute, and exhibit in any form, now or later developed, including publications for promotion on website entries and social media sites. you irrevocably and permanently waive any right to royalties or other compensation arising from or related to our use of your Testimonial, first name, and initials.</p>

            <h2>Third Party Sites</h2>
            <h3>Section 5</h3>
            <p>Our Services may require you to use websites or applications that are not Vita Bella websites or applications (collectively, “Third-Party Sites”). You acknowledge and agree that the Third-Party Sites may have different privacy policies, terms of service, user guides and/or business practices (collectively, “Third-Party Rules”) than Vita Bella, and that your use of such Third-Party Sites is governed by the respective Third-Party Rules not Vita Bella provides links to Third-Party Sites to you as a convenience, and We do not verify, make any representations, or take responsibility for such Third-Party Sites, including, without limitation, the truthfulness, accuracy, quality, or completeness of the content, application, links displayed, and/or any other activities conducted on or through such Third-Party Sites.</p>
            <p><strong>YOU AGREE THAT VITA BELLA WILL NOT, UNDER ANY CIRCUMSTANCES, BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY GOODS, APPLICATION, INFORMATION, RESOURCES, AND/OR CONTENT AVAILABLE ON OR THROUGH ANY THIRD-PARTY SITES AND/OR THIRD-PARTY DEALINGS OR COMMUNICATIONS, OR FOR ANY HARM RELATED THERETO, OR FOR ANY DAMAGES OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH USERS USE OR RELIANCE ON THE CONTENT OR BUSINESS PRACTICES OF ANY THIRD-PARTY. Any reference to any product, service, publication, institution, organization of any third-party entity, or individual, including without limitation medication brands, pharmacies, or pharmacists, does not constitute or imply Vita Bella’s endorsement or recommendation.</strong></p>

            <h2>Privacy</h2>
            <h3>Section 6</h3>
            <p>Vita Bella respects the information you provide to us. Please see our Privacy Policy for an explanation of the information that we collect from you and how we use that information. By accessing or using the Services, you acknowledge and agree to the provisions of the Privacy Policy and affirm that the Privacy Policy is a part of these terms.</p>

            <h2>Arbitration Agreement</h2>
            <h3>Section 7</h3>
            <p>You agree that any dispute between you and Vita Bella arising out of or relating to this agreement will be governed by the dispute resolution procedure outlined below. We want to address your concerns without needing a formal legal case, so we have included a tiered dispute resolution process. This Arbitration Agreement section may be modified by written agreement between you and Vita Bella.</p>
            <p><strong>Informal Resolution.</strong> Before filing a claim against Vita Bella, you agree to try to resolve the dispute informally by contacting <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. We will try to resolve the dispute informally by contacting you through email. If a dispute is not resolved within 15 days after submission, you may bring a formal proceeding, as outlined below.</p>
            <p><strong>Non-Binding Mediation.</strong> In the event of any controversy or claim arising out of or relating to this agreement or a breach of this agreement, you must first attempt to settle the dispute with non-binding mediation through the American Health Lawyers Association (“AHLA”).</p>
            <p><strong>Joint Demand.</strong> You shall, in writing, join Vita Bella in a joint demand for mediation and afterward jointly select a suitable mediator from the AHLA roster. If you and Vita Bella cannot agree upon a mediator, the AHLA shall designate one. The mediation will be conducted according to the AHLA’s Agreement to Mediate. The findings, conclusions, and recommendations of the mediator shall be non-binding, confidential, and inadmissible in arbitration or any other subsequent proceeding. Either you or Vita Bella shall have the right to bypass mediation and/or reject the Mediator’s findings, conclusions, and recommendations. In which event, all claims and disputes shall be exclusively, fully, and finally resolved using binding arbitration through the AHLA. you and Vita Bella agree to employ three (3) arbitrators (the “Panel”), where one arbitrator (1) is selected by you, one (1) is selected by Vita Bella, and the third (3rd) is selected by mutual consent of you and Vita Bella. If you and Vita Bella cannot agree upon the third arbitrator, the first two (2) arbitrators chosen shall select the third arbitrator. The selection decision shall be binding.</p>
            <p><strong>Method of Arbitration.</strong> The arbitration shall be conducted by telephone, online, and/or be solely based on written submissions—the specific manner to be chosen by the party initiating the arbitration. The arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties. Any judgment on the award rendered by the Panel may be entered in any court of competent jurisdiction. You and Vita Bella shall each pay 50% of all mediators and/or arbitrator costs, expenses, and fees incurred in connection with mediating and/or arbitrating under this agreement.</p>
            <p><strong>Time Period for Claims.</strong> Any claim or dispute arising under this agreement must be initiated for mediation and/or arbitration within two (2) years from its accrual date. Any claim or dispute initiated two (2) years or longer from its accrual date shall be time-barred and dismissed.</p>
            <p><strong>Exceptions to Agreement to Arbitrate.</strong> Vita Bella may bring a lawsuit solely for injunctive relief to stop unauthorized use or abuse of the App or infringement of intellectual property rights (for example, trademark, trade secret, copyright, or patent rights) without first engaging in the informal dispute-resolution process described above.</p>

            <h2>Additional Terms</h2>
            <p><strong>YOU MAY ONLY RESOLVE DISPUTES WITH VITA BELLA ON AN INDIVIDUAL BASIS, AND MAY NOT BRING A CLAIM AS A PLAINTIFF OR A CLASS MEMBER IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION. CLASS ARBITRATIONS, CLASS ACTIONS, PRIVATE ATTORNEY GENERAL ACTIONS, AND CONSOLIDATION WITH OTHER ARBITRATIONS ARE NOT ALLOWED UNDER THESE TERMS OF SERVICE.</strong></p>
            <p>Notwithstanding the above, you can decline or “opt out” of the alternative dispute resolution process described above by contacting <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> within 30 days of first accepting this agreement and stating that you (first and last name) decline this dispute resolution process.</p>
            <p><strong>YOU UNDERSTAND AND AGREE THAT, BY NOT OPTING OUT OF THE ALTERNATIVE DISPUTE RESOLUTION PROCESS DESCRIBED, YOU WAIVES ANY RIGHT TO JURY TRIAL TO WHICH YOU MAY OTHERWISE BE ENTITLED IN CONNECTION WITH ANY ACTION OR LITIGATION IN ANY WAY ARISING OUT OF OR RELATED TO THESE TERMS OF SERVICE.</strong></p>
            <p>If you opt-out of the dispute resolution process described in this section, or if any matter is otherwise determined not to be subject to such dispute resolution process, you hereby submit to the exclusive jurisdiction of any state or federal court sitting in the State of Nevada within thirty (30) miles of Las Vegas, Nevada in any legal proceeding arising out of or relating to this agreement. you agrees that any and all claims and matters arising out of this agreement, unless subject to the dispute resolution process described above, may be heard and determined in any such court, and you hereby waives any right to object to such filing on grounds of improper venue, forum non-convenience, or other venue-related grounds, unless such objection asserts that the claim or matter in dispute is subject to determination through the dispute resolution process described above.</p>

            <h2>General Contract Terms</h2>
            <h3>Section 8</h3>
            <p>This agreement, along with the Vita Bella Membership Package terms, pricing terms, Privacy Policy, and any additional terms or policies incorporated by reference, represents the entire agreement between you and Vita Bella concerning your account, and this Agreement supersedes and replaces any prior proposal, representation, promise or understanding relating to your account, whether oral or written.</p>
            <p><strong>Electronic Signature.</strong> By clicking “I Agree” and paying the Monthly Fee, you understand that doing so constitutes an electronic signature and forms a legally binding agreement between you and Vita Bella.</p>
            <p><strong>Changes to these Terms.</strong> Except for the Arbitration Agreement above, Vita Bella reserves the right to change or modify the terms of this agreement at any time without prior notice to you. If we materially change or modify these terms, we will let you know by sending you an email with the updated terms. Continuing to use our Services constitutes your agreement to be bound by the new terms. If you do not agree to the new terms, your only recourse is to immediately stop using the Services and delete all files associated with the Services on your device(s).</p>
            <p><strong>Waiver; Binding Effect; Counterparts.</strong> If Vita Bella chooses not to enforce any provision of this agreement, doing so will not constitute a waiver of the future enforcement of that provision or any other provision. You and Vita Bella (the “Parties”) represent and warrant that you are both authorized to execute this agreement and that this agreement, and all its terms and provisions will be binding upon and inure to the benefit of the Parties and their heirs, legal representatives, successors, and assigns. This agreement may be executed in any number of separate documents, all of which make up your agreement with Vita Bella. Facsimile and/or pdf copies of signatures shall serve as originals.</p>
            <p><strong>Governing Law and Jurisdiction.</strong> This Agreement and any disputes relating to this Agreement will be governed and construed in accordance with the laws of the United States of America and the State of Nevada, without regard for its conflicts of laws principles. Jurisdiction and Venue for any dispute concerning, involving, or in any way related to this Agreement shall lie exclusively in the federal and state courts of Nevada. The Parties expressly waive any objections to such jurisdiction and venue and irrevocably consent and submit to the personal and subject matter jurisdiction of such courts in any action or proceeding. However, this Agreement and/or any court order or judgment arising out of or related hereto shall be enforceable in every state and worldwide.</p>
            <p>By accepting and accessing services through Vita Bella, you acknowledge that you have read, understand, and agree to the terms of this agreement, including those related to arbitration, auto-renewal, and payment.</p>
        </div>
    );
};

export default TermsOfService;
